#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : kirigami2
Version  : 5.90.0
Release  : 306
URL      : https://download.kde.org/stable/frameworks/5.90/kirigami2-5.90.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.90/kirigami2-5.90.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: kirigami2-data = %{version}-%{release}
Requires: kirigami2-lib = %{version}-%{release}
BuildRequires : NetworkManager-dev
BuildRequires : appstream-dev
BuildRequires : appstream-extras
BuildRequires : attica-dev
BuildRequires : baloo-dev
BuildRequires : breeze
BuildRequires : breeze-dev
BuildRequires : breeze-gtk
BuildRequires : breeze-icons
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : buildreq-qmake
BuildRequires : extra-cmake-modules
BuildRequires : extra-cmake-modules-data
BuildRequires : fftw-dev
BuildRequires : frameworkintegration-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gmp-dev
BuildRequires : kactivities-dev
BuildRequires : kactivities-stats-dev
BuildRequires : karchive-dev
BuildRequires : kcmutils-dev
BuildRequires : kcodecs-dev
BuildRequires : kcompletion-dev
BuildRequires : kconfigwidgets-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kdecoration-dev
BuildRequires : kded-dev
BuildRequires : kdelibs4support-dev
BuildRequires : kdesignerplugin-dev
BuildRequires : kdesu-dev
BuildRequires : kdoctools-dev
BuildRequires : kemoticons-dev
BuildRequires : kfilemetadata-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kguiaddons-dev
BuildRequires : kholidays-dev
BuildRequires : ki18n-dev
BuildRequires : kiconthemes-dev
BuildRequires : kidletime-dev
BuildRequires : kinit-dev
BuildRequires : kio-dev
BuildRequires : kio-extras-dev
BuildRequires : kitemmodels-dev
BuildRequires : kitemviews-dev
BuildRequires : kjobwidgets-dev
BuildRequires : kjs-dev
BuildRequires : kjsembed-dev
BuildRequires : knotifications-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kpackage-dev
BuildRequires : kparts-dev
BuildRequires : kpeople-dev
BuildRequires : kpty-dev
BuildRequires : kquickcharts-dev
BuildRequires : krunner-dev
BuildRequires : kscreenlocker-dev
BuildRequires : ksysguard
BuildRequires : ktexteditor-dev
BuildRequires : kunitconversion-dev
BuildRequires : kwayland-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kwin-dev
BuildRequires : kwindowsystem-dev
BuildRequires : kxmlgui-dev
BuildRequires : layer-shell-qt-dev
BuildRequires : libICE-dev
BuildRequires : libSM-dev
BuildRequires : libX11-dev
BuildRequires : libXScrnSaver-dev
BuildRequires : libXau-dev
BuildRequires : libXcomposite-dev
BuildRequires : libXcursor-dev
BuildRequires : libXdamage-dev
BuildRequires : libXdmcp-dev
BuildRequires : libXext-dev
BuildRequires : libXfixes-dev
BuildRequires : libXft-dev
BuildRequires : libXi-dev
BuildRequires : libXinerama-dev
BuildRequires : libXmu-dev
BuildRequires : libXpm-dev
BuildRequires : libXrandr-dev
BuildRequires : libXrender-dev
BuildRequires : libXres-dev
BuildRequires : libXt-dev
BuildRequires : libXtst-dev
BuildRequires : libXv-dev
BuildRequires : libXxf86vm-dev
BuildRequires : libkscreen-dev
BuildRequires : libksysguard-dev
BuildRequires : libqalculate-dev
BuildRequires : libxcb-dev
BuildRequires : mesa-dev
BuildRequires : mpfr-dev
BuildRequires : networkmanager-qt-dev
BuildRequires : phonon-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickControls2)
BuildRequires : pkgconfig(Qt5QuickTest)
BuildRequires : pkgconfig(Qt5Svg)
BuildRequires : pkgconfig(iso-codes)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libpipewire-0.3)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : plasma-framework-dev
BuildRequires : plasma-wayland-protocols-dev
BuildRequires : plasma-workspace-wallpapers
BuildRequires : prison-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-staticdev
BuildRequires : qtdeclarative-dev
BuildRequires : qttools-dev
BuildRequires : qtwayland-dev
BuildRequires : solid-dev
BuildRequires : sonnet-dev
BuildRequires : syntax-highlighting-dev
BuildRequires : xcb-util-cursor-dev
BuildRequires : xcb-util-dev
BuildRequires : xcb-util-image-dev
BuildRequires : xcb-util-keysyms-dev
BuildRequires : xcb-util-renderutil-dev
BuildRequires : xcb-util-wm-dev
BuildRequires : xcb-util-xrm-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Add here, with either a script that does a git checkout
or as git submodules the two projects:

%package data
Summary: data components for the kirigami2 package.
Group: Data

%description data
data components for the kirigami2 package.


%package dev
Summary: dev components for the kirigami2 package.
Group: Development
Requires: kirigami2-lib = %{version}-%{release}
Requires: kirigami2-data = %{version}-%{release}
Provides: kirigami2-devel = %{version}-%{release}
Requires: kirigami2 = %{version}-%{release}

%description dev
dev components for the kirigami2 package.


%package lib
Summary: lib components for the kirigami2 package.
Group: Libraries
Requires: kirigami2-data = %{version}-%{release}

%description lib
lib components for the kirigami2 package.


%prep
%setup -q -n kirigami2-5.90.0
cd %{_builddir}/kirigami2-5.90.0

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643435464
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
## altflags1
unset ASFLAGS
export CFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export ASMFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export CXXFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FCFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export LDFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
export MAKEFLAGS=%{?_smp_mflags}
%global _lto_cflags 1
%global _disable_maintainer_mode 1
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
export LD_LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
export CPATH="/usr/local/cuda/include"
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH="/usr/share/defaults/fonts"
export GTK_IM_MODULE="xim"
export QT_IM_MODULE="cedilla"
export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
export NO_AT_BRIDGE=1
export GTK_A11Y=none
export PLASMA_USE_QT_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=88
export GTK_USE_PORTAL=1
export DESKTOP_SESSION=plasma
## altflags1 end
%cmake .. -DKDE_INSTALL_CONFDIR=/usr/share/xdg \
-DBUILD_TESTING:BOOL=OFF
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1643435464
rm -rf %{buildroot}
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
## altflags1
unset ASFLAGS
export CFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export ASMFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export CXXFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FCFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export FFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -fexceptions -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export LDFLAGS="-DNDEBUG -Ofast -mno-vzeroupper --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -mprefer-vector-width=256 -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -Wl,-Bsymbolic-functions -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-slp-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flive-range-shrinkage -flto=auto -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -static-libstdc++ -static-libgcc -Wl,--build-id=sha1 -Wno-inline"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
export MAKEFLAGS=%{?_smp_mflags}
%global _lto_cflags 1
%global _disable_maintainer_mode 1
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/share/pkgconfig"
export LD_LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export LIBRARY_PATH="/usr/local/nvidia/lib64:/usr/local/nvidia/lib64/gbm:/usr/local/nvidia/lib64/vdpau:/usr/local/nvidia/lib64/xorg/modules/drivers:/usr/local/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/local/nvidia/lib32:/usr/local/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
export PATH="/usr/lib64/ccache/bin:/usr/local/cuda/bin:/usr/local/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
export CPATH="/usr/local/cuda/include"
export DISPLAY=:0
export __GL_SYNC_TO_VBLANK=1
export __GL_SYNC_DISPLAY_DEVICE=HDMI-0
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=HDMI-0
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH="/usr/share/defaults/fonts"
export GTK_IM_MODULE="xim"
export QT_IM_MODULE="cedilla"
export FREETYPE_PROPERTIES="truetype:interpreter-version=40"
export NO_AT_BRIDGE=1
export GTK_A11Y=none
export PLASMA_USE_QT_SCALING=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_ENABLE_HIGHDPI_SCALING=0
export QT_FONT_DPI=88
export GTK_USE_PORTAL=1
export DESKTOP_SESSION=plasma
## altflags1 end
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kdevappwizard/templates/kirigami.tar.bz2
/usr/share/locale/ar/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ast/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/az/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ca/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ca@valencia/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/cs/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/da/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/de/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/el/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/en_GB/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/es/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/et/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/eu/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/fi/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/fr/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/gl/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/hi/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/hu/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ia/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/id/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/it/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ja/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ko/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/lt/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ml/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/nl/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/nn/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/pa/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/pl/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/pt/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/pt_BR/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ro/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ru/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/sk/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/sl/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/sr/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/sr@ijekavian/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/sr@ijekavianlatin/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/sr@latin/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/sv/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/ta/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/tg/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/tr/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/uk/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/zh_CN/LC_MESSAGES/libkirigami2plugin_qt.qm
/usr/share/locale/zh_TW/LC_MESSAGES/libkirigami2plugin_qt.qm

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/Kirigami2/KirigamiPluginFactory
/usr/include/KF5/Kirigami2/PlatformTheme
/usr/include/KF5/Kirigami2/TabletModeWatcher
/usr/include/KF5/Kirigami2/Units
/usr/include/KF5/Kirigami2/kirigami2_export.h
/usr/include/KF5/Kirigami2/kirigamipluginfactory.h
/usr/include/KF5/Kirigami2/platformtheme.h
/usr/include/KF5/Kirigami2/tabletmodewatcher.h
/usr/include/KF5/Kirigami2/units.h
/usr/lib64/cmake/KF5Kirigami2/KF5Kirigami2Config.cmake
/usr/lib64/cmake/KF5Kirigami2/KF5Kirigami2ConfigVersion.cmake
/usr/lib64/cmake/KF5Kirigami2/KF5Kirigami2Macros.cmake
/usr/lib64/cmake/KF5Kirigami2/KF5Kirigami2Targets-none.cmake
/usr/lib64/cmake/KF5Kirigami2/KF5Kirigami2Targets.cmake
/usr/lib64/libKF5Kirigami2.so
/usr/lib64/qt5/mkspecs/modules/qt_Kirigami2.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5Kirigami2.so.5
/usr/lib64/libKF5Kirigami2.so.5.90.0
/usr/lib64/qt5/qml/org/kde/kirigami.2/AboutItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/AboutPage.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/AbstractApplicationHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/AbstractApplicationItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/AbstractApplicationWindow.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/AbstractCard.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/AbstractItemViewHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/AbstractListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Action.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ActionTextField.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ActionToolBar.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ApplicationHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ApplicationItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ApplicationWindow.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Avatar.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/BasicListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Card.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/CardsGridView.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/CardsLayout.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/CardsListView.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/CheckableListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ContextDrawer.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Dialog.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/FlexColumn.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/FormLayout.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/GlobalDrawer.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Heading.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Hero.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/InlineMessage.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ItemViewHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Label.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/LinkButton.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ListItemDragHandle.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ListSectionHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/MenuDialog.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/NavigationTabBar.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/NavigationTabButton.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/OverlayDrawer.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/OverlaySheet.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Page.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/PagePoolAction.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/PageRow.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/PasswordField.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/PlaceholderMessage.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/PromptDialog.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/RouterWindow.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ScrollablePage.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/SearchField.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/Separator.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ShadowedImage.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/SwipeListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/ToolBarApplicationHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/UrlButton.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/libkirigamiplugin.so
/usr/lib64/qt5/qml/org/kde/kirigami.2/plugins.qmltypes
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/ActionButton.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/ActionIconGroup.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/ActionMenuItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/ActionsMenu.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/BannerImage.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/CardsGridViewPrivate.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/ContextDrawerActionItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/CornerShadow.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/DefaultCardBackground.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/DefaultListItemBackground.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/EdgeShadow.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/GlobalDrawerActionItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/PageActionPropertyGroup.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/PrivateActionToolButton.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/RefreshableScrollView.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/SwipeItemEventFilter.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/globaltoolbar/AbstractPageHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/globaltoolbar/BreadcrumbControl.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/globaltoolbar/PageRowGlobalToolBarStyleGroup.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/globaltoolbar/PageRowGlobalToolBarUI.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/globaltoolbar/TabBarControl.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/globaltoolbar/TitlesPageHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/private/globaltoolbar/ToolBarPageHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/qmldir
/usr/lib64/qt5/qml/org/kde/kirigami.2/settingscomponents/CategorizedSettings.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/settingscomponents/SettingAction.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/Material/AbstractListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/Material/InlineMessage.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/Material/Label.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/Material/SwipeListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/Material/Theme.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/org.kde.desktop/AbstractApplicationHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/org.kde.desktop/AbstractListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/org.kde.desktop/SwipeListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/styles/org.kde.desktop/Theme.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/PageTab.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/PrivateSwipeHighlight.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/PrivateSwipeProgress.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/PrivateSwipeStack.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/PrivateSwipeTab.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/PrivateSwipeTabBar.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/SwipeNavigator.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/TabViewLayout.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/swipenavigator/templates/PageTab.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/AbstractApplicationHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/AbstractCard.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/AbstractListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/ApplicationHeader.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/InlineMessage.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/OverlayDrawer.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/OverlaySheet.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/SingletonHeaderSizeGroup.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/SwipeListItem.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/BackButton.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/BorderPropertiesGroup.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/ContextIcon.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/ForwardButton.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/GenericDrawerIcon.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/IconPropertiesGroup.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/MenuIcon.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/PassiveNotification.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/private/ScrollView.qml
/usr/lib64/qt5/qml/org/kde/kirigami.2/templates/qmldir
